server:
  port: 8888
#  servlet:
#    context-path: /api
spring:
  application:
    name: bibe-crm
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  datasource:
    username: wxf#123
    password: fmima123#
    url: jdbc:mysql://106.55.35.69:3302/bibe_crm?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=TRUE&failOverReadOnly=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    cache-enabled: true
  type-aliases-package: com.bibe.crm.entity.po
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      #主键类型  auto:"数据库ID自增" 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #驼峰下划线转换
      table-underline: true
    banner: false

#阿里云oss配置
aliyun:
  accessKeyId: LTAI4FsDQVkzSCy5WKFZvL59
  accessKeySecret: Ywz1PXnYUq2JcGLwrli9hO0InuvbHu
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    bucketName: ibout-file-oss
    folder: lora-admin/
